///chunk_uncall_forced()

chunk_save_to_map()

ds_map_destroy(chunk_data)

ds_grid_destroy(tile_layer_bottom_grid)
ds_grid_destroy(tile_layer_middle_grid)
ds_grid_destroy(tile_layer_top_grid)
ds_grid_destroy(tile_layer_decor_grid)
ds_grid_destroy(tile_layer_bottom_background_grid)
ds_grid_destroy(tile_layer_middle_background_grid)
ds_grid_destroy(tile_layer_top_background_grid)
ds_grid_destroy(tile_layer_decor_background_grid)


instance_destroy()

