///chunk_generate_interior_room_tileID_to_obj(x, y, tile_id, switch_id)

//  tile_id   = the hex string of the tile to use
//  switch_id = the hex string of the switch to use

var xx = argument0
var yy = argument1
var tile_id = hex_to_dec(argument2)
var switch_id = hex_to_dec(argument3)

//find out which grid we're going to put this info onto
switch (switch_id)
{
  default:
    grid = obsticals_grid
  break;
}

switch (switch_id)
{
  default:
    grid[# xx, yy] = tile_id
  break;
}


//now find out what the tile data is
/*
switch (tile_id)
{
  case 0:     grid[# xx, yy] = tile_id   break; 
  case 1:     grid[# xx, yy] = tile_id   break; 
  case 2:     grid[# xx, yy] = tile_id   break; 
  case 3:     grid[# xx, yy] = tile_id   break; 
  case 4:     grid[# xx, yy] = tile_id   break; 
  case 5:     grid[# xx, yy] = tile_id   break; 
  case 6:     grid[# xx, yy] = tile_id   break; 
  case 7:     grid[# xx, yy] = tile_id   break; 
  case 8:     grid[# xx, yy] = tile_id   break; 
  case 9:     grid[# xx, yy] = tile_id   break; 
  case 10:     grid[# xx, yy] = tile_id   break; 
  case 11:     grid[# xx, yy] = tile_id   break; 
  case 12:     grid[# xx, yy] = tile_id   break; 
  case 13:     grid[# xx, yy] = tile_id   break; 
  case 14:     grid[# xx, yy] = tile_id   break; 
  case 15:     grid[# xx, yy] = tile_id   break; 
  case 16:     grid[# xx, yy] = tile_id   break; 
  case 17:     grid[# xx, yy] = tile_id   break; 
  case 18:     grid[# xx, yy] = tile_id   break; 
  case 19:     grid[# xx, yy] = tile_id   break; 
  case 20:     grid[# xx, yy] = tile_id   break; 
  case 21:     grid[# xx, yy] = tile_id   break; 
  case 22:     grid[# xx, yy] = tile_id   break; 
  case 23:     grid[# xx, yy] = tile_id   break; 
  case 24:     grid[# xx, yy] = tile_id   break; 
  case 25:     grid[# xx, yy] = tile_id   break; 
  case 26:     grid[# xx, yy] = tile_id   break; 
  case 27:     grid[# xx, yy] = tile_id   break; 
  case 28:     grid[# xx, yy] = tile_id   break; 
  case 29:     grid[# xx, yy] = tile_id   break; 
  case 30:     grid[# xx, yy] = tile_id   break; 
  case 31:     grid[# xx, yy] = tile_id   break; 
  case 32:     grid[# xx, yy] = tile_id   break; 
  case 33:     grid[# xx, yy] = tile_id   break; 
  case 34:     grid[# xx, yy] = tile_id   break; 
  case 35:     grid[# xx, yy] = tile_id   break; 
  case 36:     grid[# xx, yy] = tile_id   break; 
  case 37:     grid[# xx, yy] = tile_id   break; 
  case 38:     grid[# xx, yy] = tile_id   break; 
  case 39:     grid[# xx, yy] = tile_id   break; 
  case 40:     grid[# xx, yy] = tile_id   break; 
  case 41:     grid[# xx, yy] = tile_id   break; 
  case 42:     grid[# xx, yy] = tile_id   break; 
  case 43:     grid[# xx, yy] = tile_id   break; 
  case 44:     grid[# xx, yy] = tile_id   break; 
  case 45:     grid[# xx, yy] = tile_id   break; 
  case 46:     grid[# xx, yy] = tile_id   break; 
  case 47:     grid[# xx, yy] = tile_id   break; 
  case 48:     grid[# xx, yy] = 0   break; 
  case 49:     grid[# xx, yy] = tile_id   break; 
  case 50:     grid[# xx, yy] = tile_id   break; 
  case 51:     grid[# xx, yy] = tile_id   break; 
  case 52:     grid[# xx, yy] = tile_id   break; 
  case 53:     grid[# xx, yy] = tile_id   break; 
  case 54:     grid[# xx, yy] = tile_id   break; 
  case 55:     grid[# xx, yy] = tile_id   break; 
  case 56:     grid[# xx, yy] = tile_id   break; 
  case 57:     grid[# xx, yy] = tile_id   break; 
  case 58:     grid[# xx, yy] = tile_id   break; 
  case 59:     grid[# xx, yy] = tile_id   break; 
  case 60:     grid[# xx, yy] = tile_id   break; 
  case 61:     grid[# xx, yy] = tile_id   break; 
  case 62:     grid[# xx, yy] = tile_id   break; 
  case 63:     grid[# xx, yy] = tile_id   break; 
  case 64:     grid[# xx, yy] = tile_id   break; 
  case 65:     grid[# xx, yy] = tile_id   break; 
  case 66:     grid[# xx, yy] = tile_id   break; 
  case 67:     grid[# xx, yy] = tile_id   break; 
  case 68:     grid[# xx, yy] = tile_id   break; 
  case 69:     grid[# xx, yy] = tile_id   break; 
  case 70:     grid[# xx, yy] = tile_id   break; 
  case 71:     grid[# xx, yy] = tile_id   break; 
  case 72:     grid[# xx, yy] = tile_id   break; 
  case 73:     grid[# xx, yy] = tile_id   break; 
  case 74:     grid[# xx, yy] = tile_id   break; 
  case 75:     grid[# xx, yy] = tile_id   break; 
  case 76:     grid[# xx, yy] = tile_id   break; 
  case 77:     grid[# xx, yy] = tile_id   break; 
  case 78:     grid[# xx, yy] = tile_id   break; 
  case 79:     grid[# xx, yy] = tile_id   break; 
  case 80:     grid[# xx, yy] = tile_id   break; 
  case 81:     grid[# xx, yy] = tile_id   break; 
  case 82:     grid[# xx, yy] = tile_id   break; 
  case 83:     grid[# xx, yy] = tile_id   break; 
  case 84:     grid[# xx, yy] = tile_id   break; 
  case 85:     grid[# xx, yy] = tile_id   break; 
  case 86:     grid[# xx, yy] = tile_id   break; 
  case 87:     grid[# xx, yy] = tile_id   break; 
  case 88:     grid[# xx, yy] = tile_id   break; 
  case 89:     grid[# xx, yy] = tile_id   break; 
  case 90:     grid[# xx, yy] = tile_id   break; 
  case 91:     grid[# xx, yy] = tile_id   break; 
  case 92:     grid[# xx, yy] = tile_id   break; 
  case 93:     grid[# xx, yy] = tile_id   break; 
  case 94:     grid[# xx, yy] = tile_id   break; 
  case 95:     grid[# xx, yy] = tile_id   break; 
  case 96:     grid[# xx, yy] = tile_id   break; 
  case 97:     grid[# xx, yy] = tile_id   break; 
  case 98:     grid[# xx, yy] = tile_id   break; 
  case 99:     grid[# xx, yy] = tile_id   break; 
  case 100:     grid[# xx, yy] = tile_id   break; 
  case 101:     grid[# xx, yy] = tile_id   break; 
  case 102:     grid[# xx, yy] = tile_id   break; 
  case 103:     grid[# xx, yy] = tile_id   break; 
  case 104:     grid[# xx, yy] = tile_id   break; 
  case 105:     grid[# xx, yy] = tile_id   break; 
  case 106:     grid[# xx, yy] = tile_id   break; 
  case 107:     grid[# xx, yy] = tile_id   break; 
  case 108:     grid[# xx, yy] = tile_id   break; 
  case 109:     grid[# xx, yy] = tile_id   break; 
  case 110:     grid[# xx, yy] = tile_id   break; 
  case 111:     grid[# xx, yy] = tile_id   break; 
  case 112:     grid[# xx, yy] = tile_id   break; 
  case 113:     grid[# xx, yy] = tile_id   break; 
  case 114:     grid[# xx, yy] = tile_id   break; 
  case 115:     grid[# xx, yy] = tile_id   break; 
  case 116:     grid[# xx, yy] = tile_id   break; 
  case 117:     grid[# xx, yy] = tile_id   break; 
  case 118:     grid[# xx, yy] = tile_id   break; 
  case 119:     grid[# xx, yy] = tile_id   break; 
  case 120:     grid[# xx, yy] = tile_id   break; 
  case 121:     grid[# xx, yy] = tile_id   break; 
  case 122:     grid[# xx, yy] = tile_id   break; 
  case 123:     grid[# xx, yy] = tile_id   break; 
  case 124:     grid[# xx, yy] = tile_id   break; 
  case 125:     grid[# xx, yy] = tile_id   break; 
  case 126:     grid[# xx, yy] = tile_id   break; 
  case 127:     grid[# xx, yy] = tile_id   break; 
  case 128:     grid[# xx, yy] = tile_id   break; 
  case 129:     grid[# xx, yy] = tile_id   break; 
  case 130:     grid[# xx, yy] = tile_id   break; 
  case 131:     grid[# xx, yy] = tile_id   break; 
  case 132:     grid[# xx, yy] = tile_id   break; 
  case 133:     grid[# xx, yy] = tile_id   break; 
  case 134:     grid[# xx, yy] = tile_id   break; 
  case 135:     grid[# xx, yy] = tile_id   break; 
  case 136:     grid[# xx, yy] = tile_id   break; 
  case 137:     grid[# xx, yy] = tile_id   break; 
  case 138:     grid[# xx, yy] = tile_id   break; 
  case 139:     grid[# xx, yy] = tile_id   break; 
  case 140:     grid[# xx, yy] = tile_id   break; 
  case 141:     grid[# xx, yy] = tile_id   break; 
  case 142:     grid[# xx, yy] = tile_id   break; 
  case 143:     grid[# xx, yy] = tile_id   break; 
  case 144:     grid[# xx, yy] = tile_id   break; 
  case 145:     grid[# xx, yy] = tile_id   break; 
  case 146:     grid[# xx, yy] = tile_id   break; 
  case 147:     grid[# xx, yy] = tile_id   break; 
  case 148:     grid[# xx, yy] = tile_id   break; 
  case 149:     grid[# xx, yy] = tile_id   break; 
  case 150:     grid[# xx, yy] = tile_id   break; 
  case 151:     grid[# xx, yy] = tile_id   break; 
  case 152:     grid[# xx, yy] = tile_id   break; 
  case 153:     grid[# xx, yy] = tile_id   break; 
  case 154:     grid[# xx, yy] = tile_id   break; 
  case 155:     grid[# xx, yy] = tile_id   break; 
  case 156:     grid[# xx, yy] = tile_id   break; 
  case 157:     grid[# xx, yy] = tile_id   break; 
  case 158:     grid[# xx, yy] = tile_id   break; 
  case 159:     grid[# xx, yy] = tile_id   break; 
  case 160:     grid[# xx, yy] = tile_id   break; 
  case 161:     grid[# xx, yy] = tile_id   break; 
  case 162:     grid[# xx, yy] = tile_id   break; 
  case 163:     grid[# xx, yy] = tile_id   break; 
  case 164:     grid[# xx, yy] = tile_id   break; 
  case 165:     grid[# xx, yy] = tile_id   break; 
  case 166:     grid[# xx, yy] = tile_id   break; 
  case 167:     grid[# xx, yy] = tile_id   break; 
  case 168:     grid[# xx, yy] = tile_id   break; 
  case 169:     grid[# xx, yy] = tile_id   break; 
  case 170:     grid[# xx, yy] = tile_id   break; 
  case 171:     grid[# xx, yy] = tile_id   break; 
  case 172:     grid[# xx, yy] = tile_id   break; 
  case 173:     grid[# xx, yy] = tile_id   break; 
  case 174:     grid[# xx, yy] = tile_id   break; 
  case 175:     grid[# xx, yy] = tile_id   break; 
  case 176:     grid[# xx, yy] = tile_id   break; 
  case 177:     grid[# xx, yy] = tile_id   break; 
  case 178:     grid[# xx, yy] = tile_id   break; 
  case 179:     grid[# xx, yy] = tile_id   break; 
  case 180:     grid[# xx, yy] = tile_id   break; 
  case 181:     grid[# xx, yy] = tile_id   break; 
  case 182:     grid[# xx, yy] = tile_id   break; 
  case 183:     grid[# xx, yy] = tile_id   break; 
  case 184:     grid[# xx, yy] = tile_id   break; 
  case 185:     grid[# xx, yy] = tile_id   break; 
  case 186:     grid[# xx, yy] = tile_id   break; 
  case 187:     grid[# xx, yy] = tile_id   break; 
  case 188:     grid[# xx, yy] = tile_id   break; 
  case 189:     grid[# xx, yy] = tile_id   break; 
  case 190:     grid[# xx, yy] = tile_id   break; 
  case 191:     grid[# xx, yy] = tile_id   break; 
  case 192:     grid[# xx, yy] = tile_id   break; 
  case 193:     grid[# xx, yy] = tile_id   break; 
  case 194:     grid[# xx, yy] = tile_id   break; 
  case 195:     grid[# xx, yy] = tile_id   break; 
  case 196:     grid[# xx, yy] = tile_id   break; 
  case 197:     grid[# xx, yy] = tile_id   break; 
  case 198:     grid[# xx, yy] = tile_id   break; 
  case 199:     grid[# xx, yy] = tile_id   break; 
  case 200:     grid[# xx, yy] = tile_id   break; 
  case 201:     grid[# xx, yy] = tile_id   break; 
  case 202:     grid[# xx, yy] = tile_id   break; 
  case 203:     grid[# xx, yy] = tile_id   break; 
  case 204:     grid[# xx, yy] = tile_id   break; 
  case 205:     grid[# xx, yy] = tile_id   break; 
  case 206:     grid[# xx, yy] = tile_id   break; 
  case 207:     grid[# xx, yy] = tile_id   break; 
  case 208:     grid[# xx, yy] = tile_id   break; 
  case 209:     grid[# xx, yy] = tile_id   break; 
  case 210:     grid[# xx, yy] = tile_id   break; 
  case 211:     grid[# xx, yy] = tile_id   break; 
  case 212:     grid[# xx, yy] = tile_id   break; 
  case 213:     grid[# xx, yy] = tile_id   break; 
  case 214:     grid[# xx, yy] = tile_id   break; 
  case 215:     grid[# xx, yy] = tile_id   break; 
  case 216:     grid[# xx, yy] = tile_id   break; 
  case 217:     grid[# xx, yy] = tile_id   break; 
  case 218:     grid[# xx, yy] = tile_id   break; 
  case 219:     grid[# xx, yy] = tile_id   break; 
  case 220:     grid[# xx, yy] = tile_id   break; 
  case 221:     grid[# xx, yy] = tile_id   break; 
  case 222:     grid[# xx, yy] = tile_id   break; 
  case 223:     grid[# xx, yy] = tile_id   break; 
  case 224:     grid[# xx, yy] = tile_id   break; 
  case 225:     grid[# xx, yy] = tile_id   break; 
  case 226:     grid[# xx, yy] = tile_id   break; 
  case 227:     grid[# xx, yy] = tile_id   break; 
  case 228:     grid[# xx, yy] = tile_id   break; 
  case 229:     grid[# xx, yy] = tile_id   break; 
  case 230:     grid[# xx, yy] = tile_id   break; 
  case 231:     grid[# xx, yy] = tile_id   break; 
  case 232:     grid[# xx, yy] = tile_id   break; 
  case 233:     grid[# xx, yy] = tile_id   break; 
  case 234:     grid[# xx, yy] = tile_id   break; 
  case 235:     grid[# xx, yy] = tile_id   break; 
  case 236:     grid[# xx, yy] = tile_id   break; 
  case 237:     grid[# xx, yy] = tile_id   break; 
  case 238:     grid[# xx, yy] = tile_id   break; 
  case 239:     grid[# xx, yy] = tile_id   break; 
  case 240:     grid[# xx, yy] = tile_id   break; 
  case 241:     grid[# xx, yy] = tile_id   break; 
  case 242:     grid[# xx, yy] = tile_id   break; 
  case 243:     grid[# xx, yy] = tile_id   break; 
  case 244:     grid[# xx, yy] = tile_id   break; 
  case 245:     grid[# xx, yy] = tile_id   break; 
  case 246:     grid[# xx, yy] = tile_id   break; 
  case 247:     grid[# xx, yy] = tile_id   break; 
  case 248:     grid[# xx, yy] = tile_id   break; 
  case 249:     grid[# xx, yy] = tile_id   break; 
  case 250:     grid[# xx, yy] = tile_id   break; 
  case 251:     grid[# xx, yy] = tile_id   break; 
  case 252:     grid[# xx, yy] = tile_id   break; 
  case 253:     grid[# xx, yy] = tile_id   break; 
  case 254:     grid[# xx, yy] = tile_id   break; 
  case 255:     grid[# xx, yy] = tile_id   break; }



